### ISSUE TITLE
Add replace transducer?

### ISSUE THREAD

**Issue by snorremd** [paren-com/serene#3]
Hello!

First of all. Thanks for an excellent library. I've already been able to make use of it in a project I'm working on.

I was wondering if you think it would be worth considering having a `:replace` option in the compiler options map?

One use case I encountered where this is useful is the need to replace `string?` specs with `uuid?` for attributes with type `ID`. This was necessary as I use the serialize and de-serialize functionality in Lacinia to convert GraphQL ID string values to and from uuid values. I think replacing specs might become a common use case for users of Serene.

Currently I achieve the replace functionality by using a custom transducer as hinted to by your documentation.

```clojure
(defmethod compiler/transducer :replace [_ replace-fn]
  (map (fn [{:as spec
             ::transducers/keys [alias?]
             ::compiler/keys [form schema-key]}]
         (if-let [rep (and
                        (not alias?)
                        (replace-fn schema-key))]
           (assoc spec ::compiler/form `~rep)
           spec))))

;; And the option map
(def options {:replace {:ID `uuid?}})
```

This is as you can see a blue copy of the extend transducer. It would be easy to add it to the serene library without much code duplication.

**Comment by domkm** [comment]
Hi @snorremd,

Apologies for my slow response. I was away on vacation.

Thank you for the suggestion! I'm happy to hear that you are finding Serene to be helpful.

I have two concerns with adding a `:replace` option.

1. This would cause the options to be order-dependant. The following two option maps would behave differently.
```clojure
;; extends the replaced spec
{:replace {:User `user?}
 :extend {:User `account?}}

;; replaces the extended spec
{:extend {:User `account?}
 :replace {:User `user?}}
```
I think this would be a subtle and confusing bug so, if possible, it would be great to avoid order-dependent options. Have you considered a way of implementing `:replace` that avoids this issue? Perhaps compilation could error if `:extend` ran before `:replace`, but that doesn't feel ideal.

2. I considered a similar option initially but couldn't come up with a sufficiently good use-case for it. 

As long as you are serializing IDs as Strings, then I think you are abiding by the [GraphQL spec](https://facebook.github.io/graphql/June2018/#sec-ID). Unfortunately, the serialized vs non-serialized context of scalars is not something that Serene deals with. As such, if you have scalars that serialize differently, then Serene can only be used for validation/generation of non-serialized values. Perhaps you could consider using a custom scalar like `scalar UUID` that doesn't have the GraphQL spec requirements?

I'm hoping that the next version of clojure.spec (announced by Rich Hickey at Clojure/conj) will provide functionality for specs to have context-dependent semantics so that Serene can be useful for both serialized and non-serialized values.

I will continue thinking about adding a `:replace` option. Fortunately, compilation options are extensible so you have already implemented an easy solution for your project. For the time being, I would recommend that you continue to use your custom transducer but consider using a namespaced key like `:snorremd/replace` in case we add a `:replace` that has different semantics.

**Comment by snorremd** [comment]
No need for apologies, you are giving out this library for free (beer and license both).

> 1. This would cause the options to be order-dependant. The following two option maps would behave differently.

I had not considered that the implicit order dependency of the options could cause subtle behavior variations. Very good point!

> As such, if you have scalars that serialize differently, then Serene can only be used for validation/generation of non-serialized values. 

Yeah. Because I replace the parse and serialize function for the `ID` scalar in Lacinia to deal with UUIDs I'm more or less breaking Serene's correct assumption that `ID` scalars are simple strings. When trying to istrument my resolver functions (which deals with the parsed UUID data values), this breaks down unless I replace the ID specs with `uuid?`. Of course doing this presents its own problem; I now cannot use the specs to validate input and output before Lacinia works on the data. So in tests where I use Lacinia's `execute` function and get normal serialized IDs back I won't be able to directly validate the output with the serene specs:

```clojure
(lacinia/execute
  compiled-schema
  create-mutation
  {}
  {}) => {:id "63188bdd-1716-459b-82f1-9302f1aa27a7"}
```

Edit: The effect where adding Lacinia parsers and serializers for any scalar will probably have this effect. It is not possible for one spec to handle both cases. It would for example make sense for a spec used to instrument the resolver function that returns a Date to use `inst?`, but for specs used to validate test output from graphql queries to match ISO date strings. In essence I think I just might need separate specs for graphql test output and those used to instrument the resolver functions. 

> I would recommend that you continue to use your custom transducer but consider using a namespaced key like :snorremd/replace

Will do. I'll close this issue now that you've shared your thoughts.
