### ISSUE TITLE
Lacinia turns enum values into keywords; Serene expects strings

### ISSUE THREAD

**Issue by solussd** [paren-com/serene#6]
Would it be possible to control this in serene?

**Comment by solussd** [comment]
I hacked around this using the transducer multimethod, but it would be nice to be able to configure the enum behavior (e.g., whether or not to generate specs for each enum value, coercing to other types, etc.).

**Comment by domkm** [comment]
I'm open to something like this but I would prefer a more generic solution that allows customization of other scalars as well. I'm hesitant to address this currently because spec2 will be more capable of reifying context, which is very relevant for GraphQL. For example, an enum might be a string as serialized input, a keyword as parsed input, and a string as both serialized and parsed output (depending on the client). See https://github.com/paren-com/serene/issues/3#issuecomment-446726625 for more info.
