### ISSUE TITLE
Spec cannot be satisfied

### ISSUE THREAD

**Issue by se-neaxplore** [paren-com/serene#8]
Using a custom scalar `scalar Timestamp` generates a spec `clojure.core/any?`.  Extending this scalar with `clojure.core/inst?` results in 
`(clojure.spec.alpha/and clojure.core/any? clojure.core/inst?)` Which is still not satisfiable by clojure spec.

Swapping the clauses `(clojure.spec.alpha/and clojure.core/inst? clojure.core/any?)` solves this problem.

Proposal: Change the generated spec to put the extended spec first.

I think the change should be introduced here [defmethod compiler/transducer :extend](https://github.com/paren-com/serene/blob/3e3a33b1dac69144dd8f0d9b839a0b6de8311ba3/sources/main/paren/serene/compiler/transducers.cljc#L45)

Let me know what you think and if you would like to move forward with this, I will make a PR.

**Comment by domkm** [comment]
Sure, PR welcome. It's been a long time since I've looked at this code, so I don't recall if this is feasible, but perhaps we could drop the default `any?` when extending instead of always `and`ing.

Aside, do you know why `(clojure.spec.alpha/and clojure.core/any? clojure.core/inst?)` is not satisfiable? That is surprising to me.

**Comment by se-neaxplore** [comment]
Removing `(clojure.core/any?)` would solve it directly.

The `(s/and)` generator uses the first generator to generate a value which is than passed to the next spec. `any?` generates a lot of different values but never an `Inst`.

`(gen/sample (s/gen (s/and clojure.core/any? string?)))` this expression works sometimes, because `any?` generates `String`.
